<?php
/**
 * This is the default template part for the membership product restriction
 * purchase requirement element.
 *
 * @since 1.4.0
 * @version 1.4.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/ directory located in your theme.
 */

$product_id = it_exchange_get_product_feature( $GLOBALS['it_exchange']['product']->ID, 'membership-product-restriction', array( 'field' => 'membership_product' ) );
?>

<?php do_action( 'it_exchange_mpr_addon_before_purchase_requirement' ); ?>
	<div class="it-exchange-checkout-purchase-requirements-notification">
		<?php do_action( 'it_exchange_mpr_addon_begin_purchase_requirement' ); ?>

		<?php echo it_exchange_mpr_addon_get_purchase_requirement_message( $product_id ); ?>

		<?php do_action( 'it_exchange_mpr_addon_end_purchase_requirement' ); ?>
	</div>
<?php do_action( 'it_exchange_mpr_addon_after_purchase_requirement' ); ?>